$Step-1$:
    
**Import required packages**

In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

$Step-2$

**Read the data**

In [36]:
# read the dataset 
file="C:\\Users\\HP\\Desktop\\gkp\winequality_red.csv"
df = pd.read_csv(file)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7.4,0.70,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7.8,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df=df.dropna()
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0
3,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5.0
5,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5.0
7,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.0
9,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5.0

In [38]:
df.shape

(1599, 12)

In [39]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [40]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [41]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                 float64
dtype: object

- We divide data into two parts i.e input data and output data

- input data = X; output data=y

- Again we divide input data into two parts i.e train and test

- input train data= x_train; input test data= x_test

- similarly we divide output data into two parts i.e train and test

- output train data= y_train; output test data= y_test

- Model development happens on train data i.e x_train and y_train

- Model will predict by passing x_test data, these are called y_predictions

- y_predictions will compare with y_test , this is called test accuracy/ test error

In [42]:
#x_train   y_train
#1           1
#2           4
#3           9
#4           16

#x_test    y_test
#5         25

#develope a model (1,1) (2,4) (3,9) (4,16)
#model will predict by passing 5 , y_predictions  we need to compare with y_test

$Step-3$

**divide data into input and output data**

In [43]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [44]:
X=df.drop('quality',axis=1)
y=df['quality']
X

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
3,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
5,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
7,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
9,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
3189,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
3191,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
3193,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
3195,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
3197,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

$Step-4$

**Divide data into train and test**

- Will use train test split from sklearn model selection

- It will take following parameters

    - X: input data
    
    - y: output data
    
    - test size = 0.3, 30% test data 70% train data
    
    - by default 75:25
    
    - random state
    
        - we want select observations randomly
        
        - many possibile combinations
        
        - Every possibile combination represent as a number
        
        - 1,2,3,4,5,6,7,8,9,10
        
        - Select 5 numbers randomly : how many combiantions
        
        - random state=42 
        
        - random state= 1234

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,  # Input data
                                                  y,  # output data
                                                  random_state=1234, # it select random samples
                                                  test_size=0.30)

**Check point-1**

$Check$ $the$ $shape$

In [46]:
#df.shape
#X:11   y:1
#1599 = 100
#?    = 30

#1599*30/100

#test data has  480
#train data has 1599-480=1119 

#df      : 12  column  1599 rows   (1599,12)
#X_train : 11 columns  1119 rows   (1119,11)
#X_test  : 11 columns   480 rows   (480,11)
#y_train :  1  column  1119 rows   (1119,)
#y_test  :  1  column   480 rows   (480,)


# if you seee shape  (rows,columns) (480,1) === data farme
# if you see  shape  (rows,)        (480,)  === series

In [47]:
X_train.shape, X_test.shape

((1119, 11), (480, 11))

In [48]:
y_train.shape, y_test.shape

((1119,), (480,))

In [49]:
print("the shape of data frame is:",df.shape)
print("the shape of X_train is:",X_train.shape)
print("the shape of X_test frame is:",X_test.shape)
print("the shape of y_train frame is:",y_train.shape)
print("the shape of y_test frame is:",y_test.shape)

the shape of data frame is: (1599, 12)
the shape of X_train is: (1119, 11)
the shape of X_test frame is: (480, 11)
the shape of y_train frame is: (1119,)
the shape of y_test frame is: (480,)

**Check point-2**:
    
- Check the observation indexes of X_train and y_train both should match
    
- similarly X_test and y_test both should match

In [50]:
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1285,9.9,0.540,0.45,2.3,0.071,16.0,40.0,0.99910,3.39,0.62,9.4
1357,8.3,0.780,0.10,2.6,0.081,45.0,87.0,0.99830,3.48,0.53,10.0
825,7.1,0.735,0.16,1.9,0.100,15.0,77.0,0.99660,3.27,0.64,9.3
147,8.3,0.675,0.26,2.1,0.084,11.0,43.0,0.99760,3.31,0.53,9.2
1971,7.4,0.580,0.00,2.0,0.064,7.0,11.0,0.99562,3.45,0.58,11.3
...,...,...,...,...,...,...,...,...,...,...,...
2457,5.1,0.420,0.00,1.8,0.044,18.0,88.0,0.99157,3.68,0.73,13.6
2155,8.6,0.370,0.65,6.4,0.080,3.0,8.0,0.99817,3.27,0.58,11.0
2637,7.5,0.630,0.27,2.0,0.083,17.0,91.0,0.99616,3.26,0.58,9.8
1447,7.1,0.310,0.30,2.2,0.053,36.0,127.0,0.99650,2.94,1.62,9.5
1631,10.8,0.450,0.33,2.5,0.099,20.0,38.0,0.99818,3.24,0.71,10.8

In [51]:
y_train

1285    5.0
1357    5.0
825     5.0
147     4.0
1971    6.0
       ...
2457    7.0
2155    5.0
2637    6.0
1447    5.0
1631    5.0
Name: quality, Length: 1119, dtype: float64

In [52]:
X_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1377,7.7,0.660,0.04,1.6,0.039,4.0,9.0,0.99620,3.40,0.47,9.4
1923,7.1,0.560,0.14,1.6,0.078,7.0,18.0,0.99592,3.27,0.62,9.3
1453,8.1,0.720,0.09,2.8,0.084,18.0,49.0,0.99940,3.43,0.72,11.1
1075,8.1,0.825,0.24,2.1,0.084,5.0,13.0,0.99720,3.37,0.77,10.7
3089,8.4,0.370,0.43,2.3,0.063,12.0,19.0,0.99550,3.17,0.81,11.2
...,...,...,...,...,...,...,...,...,...,...,...
2923,6.2,0.785,0.00,2.1,0.060,6.0,13.0,0.99664,3.59,0.61,10.0
3183,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6
2091,6.9,0.440,0.00,1.4,0.070,32.0,38.0,0.99438,3.32,0.58,11.4
2997,6.6,0.895,0.04,2.3,0.068,7.0,13.0,0.99582,3.53,0.58,10.8
85,7.5,0.490,0.20,2.6,0.332,8.0,14.0,0.99680,3.21,0.90,10.5

In [53]:
y_test

1377    5.0
1923    5.0
1453    6.0
1075    6.0
3089    7.0
       ...
2923    4.0
3183    6.0
2091    6.0
2997    6.0
85      6.0
Name: quality, Length: 480, dtype: float64

In [54]:
df.reset_index(drop=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5.0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5.0
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5.0
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6.0
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5.0
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6.0
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5.0
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6.0

In [56]:
# ############## All together ##############
# #Step-1: Import packages
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import warnings
# warnings.filterwarnings('ignore')

# # Step-2:  Read the data
# df = pd.read_csv("C:\\Users\\omkar\\OneDrive\\Documents\\Data science\\Naresh IT\\Datafiles\\winequality_red.csv")
# df.head()

# # Step-3(Optional): If you are seeing any duplicates
# #         or data has empty rows when you read it display as NuLL  or NaN
# #         if you are seeing this check it is really a missing values  
# #         or  data has empty rows (alternative rows)
# df.dropna(inplace=True)
# df.reset_index(inplace=True)

# ##################### EDA ##################
# #Numerical data  shoudl be ready  before go to the step-4 
# ############################################# 

# # Step-4: Divide into X and y
# X=df.drop('quality',axis=1)
# y=df['quality']

# # Step-5: Train test split
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test=train_test_split(X,  # Input data
#                                                   y,  # output data
#                                                   random_state=1234, # it select random samples
#                                                   test_size=0.30)

$Step-5$

**Model development**

In [57]:
# Model development happens using train data
# X_train    y_train
#from sklearn.linear_model import LinearRegression
#LR=LinearRegression()

In [58]:
X_train.ndim
# 1 dimension means 1 column only
# 2 dimension means 2 column only
# when you have only 1 coulmn, the shape will not show the coulumn
# (21,) it is only one column data having 21 observations
# (9,) it is one column data having 9 observation
# (30,2) it is 2 column data having 30 observation
# Reshape the data if you have only one column

2

- import the package

- save the pacakge

- apply fit transform

In [60]:
from sklearn.preprocessing import LabelEncoder,StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes
from sklearn.neighbors
from sklearn.ensemble

SyntaxError: invalid syntax (3662612347.py, line 5)

In [61]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

$Step-6$

**Model predictions**

we need to pass X_test data

In [27]:
# Model predictions happens X_test
y_predictions=LR.predict(X_test)

In [28]:
y_predictions

array([5.15272674, 5.32546327, 5.63662519, 5.51245819, 6.35588496,
       5.39028618, 5.37580837, 5.94379165, 5.49446987, 6.98211458,
       4.92847919, 5.18177228, 5.73271386, 5.56085417, 5.53985028,
       5.25272042, 4.93424659, 5.12423646, 6.27626835, 5.12589226,
       5.06691612, 5.91039778, 5.1797551 , 5.45854364, 5.72531378,
       6.31002431, 5.30913419, 5.50678991, 6.04808131, 5.47609822,
       4.72291628, 6.20818055, 5.21920961, 5.62421184, 5.55062526,
       5.52259916, 6.36735043, 5.23288886, 5.49938736, 5.80792898,
       5.16587916, 6.13318292, 5.72636822, 5.33537114, 5.63701918,
       4.96463531, 4.88029661, 5.78938553, 6.36333952, 5.56149953,
       4.95005899, 5.75085354, 6.67236186, 6.16951277, 5.34056761,
       5.12096361, 6.19641543, 5.21584694, 6.46449078, 5.25590493,
       5.27667097, 5.17871421, 5.09122333, 5.63083824, 5.01946398,
       6.16336001, 5.7427919 , 6.337122  , 5.28732968, 6.05063646,
       5.7342916 , 5.57340483, 5.21043842, 6.18633591, 5.50678991,
       5.3453067 , 5.99997768, 6.51564794, 4.85375662, 5.04018732,
       5.72499592, 5.59626211, 5.73949584, 5.95489086, 5.34697269,
       4.99839179, 6.13681154, 5.32302661, 6.01068016, 6.12678637,
       6.52768314, 5.39538409, 5.9974906 , 4.99004327, 5.44790697,
       5.86843828, 5.26806983, 6.65075932, 6.61072464, 5.99997768,
       5.37579844, 5.48785095, 4.94241599, 5.53013394, 5.51054593,
       5.25914217, 5.89858025, 5.16978949, 5.40527552, 5.44913755,
       6.38388834, 5.54138872, 6.22755065, 5.35050741, 5.55565805,
       5.69996464, 5.35611312, 5.91795566, 6.84295266, 5.21736143,
       5.93685756, 6.02728227, 5.65516136, 6.33585096, 6.11727608,
       5.10631555, 5.21930664, 6.51527783, 6.29685541, 6.23764222,
       5.2792288 , 5.03871695, 5.88172061, 5.0851889 , 5.27738598,
       6.35828943, 5.89939941, 5.45905811, 5.41928796, 5.57217489,
       5.93356169, 4.83777751, 5.43045252, 5.14580263, 5.75145727,
       5.77227893, 5.20511824, 6.22744476, 6.15111159, 5.37199058,
       5.43837324, 5.77768114, 6.61866538, 6.74493635, 5.99429439,
       5.77421449, 5.71445701, 5.63158268, 6.53617359, 5.61226567,
       6.41524291, 5.85713158, 6.03657959, 5.36589905, 5.79504901,
       6.15045308, 5.34746564, 4.18492552, 5.78179004, 5.9409628 ,
       4.87152252, 5.75689927, 4.97026015, 5.74576868, 6.55745611,
       6.04292031, 5.32973134, 5.52682185, 5.71987688, 4.93131525,
       6.04719996, 5.20606774, 5.85001588, 6.56279324, 5.22784496,
       5.13583528, 6.49406669, 6.67080913, 5.86790849, 6.22543582,
       5.99898464, 5.48676406, 4.68758173, 6.42891816, 5.3780084 ,
       4.72596428, 5.35624776, 6.98166918, 5.30720706, 5.01009976,
       5.9095069 , 5.89788367, 5.74541352, 4.97661924, 6.64061995,
       5.56824532, 5.88970167, 5.10254921, 5.03266072, 4.78859962,
       5.66137988, 5.01756041, 5.70331509, 5.08378929, 5.91679978,
       6.69986908, 5.31928286, 5.34669749, 5.31734828, 5.6188404 ,
       5.6103356 , 5.88657821, 4.82255134, 5.47617034, 5.82141836,
       4.96924459, 5.45555462, 6.15466593, 5.60961275, 5.97937907,
       6.29141847, 5.49532602, 5.7427919 , 5.02129556, 5.42567123,
       5.30376592, 6.44506134, 5.79457654, 5.85840874, 6.40681931,
       5.23356207, 5.09446531, 6.29040996, 5.23133575, 5.20440993,
       4.91613205, 4.85264526, 5.77402591, 6.44998907, 6.27228383,
       5.66752455, 5.77214065, 6.2457379 , 5.01756041, 5.88530413,
       5.46922842, 5.31254547, 5.16197206, 5.84930403, 5.45790288,
       5.45284814, 5.0309555 , 6.11126538, 6.39353084, 5.95035988,
       6.16294412, 6.11799254, 5.859645  , 5.32664826, 5.34056761,
       5.06423962, 5.32051406, 5.43624309, 5.33971951, 5.58178758,
       5.75588456, 6.04024883, 4.91167335, 5.60170434, 5.32877713,
       6.22983414, 5.89614721, 5.93360527, 5.39888101, 5.2739361 ,
       5.73794177, 5.86555862, 5.03944697, 5.32346217, 5.74101128,
       6.40284138, 5.96305686, 4.93108229, 5.90456997, 5.71279268,
       5.61244954, 5.14567686, 5.36421345, 4.96924459, 5.38200614,
       5.93259413, 6.61817345, 5.9401426 , 5.09222651, 6.59461735,
       6.37818219, 5.76677648, 5.00550284, 5.6642651 , 5.09132685,
       5.35617409, 5.0856266 , 5.76205873, 5.58353651, 6.11360811,
       5.26670428, 5.1502229 , 6.35872853, 5.78881572, 5.12077223,
       6.20379015, 5.12846456, 5.245733  , 5.62421184, 5.33216794,
       4.63391647, 6.67080913, 5.30197384, 6.07737771, 5.08945872,
       6.3404451 , 5.00101501, 5.76082175, 4.78681399, 5.43540031,
       5.5933712 , 5.20854044, 5.53965055, 5.51286652, 6.09119691,
       6.89645836, 6.5818963 , 6.51616813, 6.7389971 , 5.13583528,
       5.04542379, 5.55565805, 5.81421595, 5.8596704 , 5.5371316 ,
       5.52159867, 6.08766214, 5.33673345, 5.21641764, 5.5881843 ,
       4.83649958, 6.54755782, 6.15975664, 5.18758997, 5.543044  ,
       6.37948308, 5.27430664, 5.41978692, 5.95011166, 6.15443962,
       5.43156985, 5.17851884, 5.71776488, 5.31049826, 6.29287608,
       5.16405155, 5.51987093, 5.94985843, 5.45261618, 6.1957446 ,
       6.22450256, 6.34398536, 5.02138294, 5.08230935, 5.63470779,
       5.75689927, 5.56268525, 4.61066841, 5.6356401 , 5.91613694,
       4.96621268, 5.10918278, 5.66306872, 4.79517341, 5.79608951,
       6.11360811, 6.23317938, 5.15817553, 5.66531897, 5.37580837,
       5.25189877, 6.5720807 , 5.24409385, 5.55140543, 6.45336013,
       6.40942246, 4.83234267, 5.30326782, 4.96473992, 7.52775146,
       5.42951778, 6.38524949, 6.37419061, 6.63801798, 6.05922706,
       5.73767049, 6.03642831, 4.83223993, 6.24020332, 5.72479784,
       5.18607442, 5.05450429, 5.11697949, 5.13412713, 5.52440323,
       5.64867525, 4.98224538, 6.09363224, 5.44051117, 5.81230694,
       5.46789186, 4.55788622, 6.4346495 , 6.83493526, 5.55577486,
       5.78380845, 6.26550268, 5.16451239, 5.64312174, 5.19935697,
       6.36699511, 4.96641745, 5.86934155, 5.76462945, 6.36547688,
       5.57273104, 5.67822167, 5.3098559 , 5.32346217, 5.80379403,
       5.05273644, 4.89716249, 4.94106077, 4.39448333, 5.35399193,
       5.95011166, 5.47056853, 5.09916641, 6.15419278, 5.32886401,
       5.55946617, 6.39503255, 5.51496826, 5.09226489, 5.98738087,
       6.16951277, 5.66535961, 4.85264526, 5.32570564, 6.08694216,
       5.71886682, 6.18670867, 5.16933689, 5.47617034, 5.1985077 ,
       5.37466118, 5.4969461 , 5.11061722, 5.07457111, 6.43458746,
       5.16307079, 5.55639097, 6.16741756, 5.27142375, 5.67409146])

$Step-7$

**Model evaluation**

In [29]:
# RMSE
# MSE
# MAE
# R-square

from sklearn.metrics import r2_score,mean_squared_error

In [30]:
R2=r2_score(y_test,y_predictions)
MSE=mean_squared_error(y_test,y_predictions)
#MSE**(1/2)
RMSE=np.sqrt(MSE)
#accuracy_score(y_test,y_predictions) # it is a regression tech
print("R-sqaure:",R2)
print("MSE:",MSE)
print("RMSE:",RMSE)

R-sqaure: 0.31285862790752406
MSE: 0.39185847231164284
RMSE: 0.6259860000923686

In [31]:
# Suppose your original salary is 50k
# Our model will expecting either 44k  or  56k

$Step-8$

**Finding coeffiecnt and Intercept**

- Coefficient means b0 ,b1 ,b2....

- Coeffiecints depends on number of input features

- In this data we have only one column as input i.e. Years of Experience

- So we will get only one coeffiecnt

In [31]:
LR.coef_
print("The coeffiecnt of Years_of_experience is:",LR.coef_)

The coeffiecnt of Years_of_experience is: [ 2.86163946e-02 -1.17907625e+00 -2.55897983e-01  4.14316493e-03
 -1.54784393e+00  6.49596171e-03 -3.95580696e-03 -1.20899746e+01
 -4.30288140e-01  9.60801101e-01  2.93739795e-01]

In [32]:
LR.intercept_

16.07844379344555

In [33]:
X_train.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [35]:
#Regression_equation=LR.intercept_+LR.coef_ * col namee
#Regression_equation

y=16.07+2.86163946e-02*fixed acidity+-1.17907625e+00*volatile acidity

$Step-9$

**Plot the regression line**

- In order to plot regression line

- We need to undertsand the two plots

- Orginal data plot i.e input data(X) vs output data(y)

- Regression plot i.e input data (X) vs predictions of regression model by passing input data (X)

In [27]:
# Draw the regression line on original data vs predictions on original data

#original_y_predictions=LR.predict(X.array.reshape(-1,1))
#plt.scatter(X,y,label='original data')  # Original plot
#plt.plot(X,original_y_predictions,color='red') # Regression plot

$Step-10$

**Stas.OLS method**

In [28]:
from statsmodels.api import OLS
OLS(y_train,X_train).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                quality   R-squared (uncentered):                   0.987
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              7512.
Date:                Mon, 09 Oct 2023   Prob (F-statistic):                        0.00
Time:                        08:00:13   Log-Likelihood:                         -1115.2
No. Observations:                1119   AIC:                                      2252.
Df Residuals:                    1108   BIC:                                      2308.
Df Model:                          11
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
fixed acidity            0.0133      0.020      0.664      0.507      -0.026       0.053
volatile acidity        -1.1899      0.142     -8.354      0.000      -1.469      -0.910
citric acid             -0.2557      0.178     -1.434      0.152      -0.606       0.094
residual sugar          -0.0025      0.014     -0.178      0.859      -0.031       0.025
chlorides               -1.5735      0.494     -3.182      0.002      -2.544      -0.603
free sulfur dioxide      0.0067      0.003      2.530      0.012       0.001       0.012
total sulfur dioxide    -0.0040      0.001     -4.260      0.000      -0.006      -0.002
density                  4.3073      0.768      5.606      0.000       2.800       5.815
pH                      -0.5074      0.196     -2.587      0.010      -0.892      -0.123
sulphates                0.9424      0.133      7.109      0.000       0.682       1.203
alcohol                  0.3085      0.022     14.229      0.000       0.266       0.351
==============================================================================
Omnibus:                       13.594   Durbin-Watson:                   2.099
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.983
Skew:                          -0.165   Prob(JB):                     0.000205
Kurtosis:                       3.506   Cond. No.                     2.41e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 2.41e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
## All together

################################## Data into two parts############################################
X=df['YearsExperience']  
y=df['Salary']


################################ Train test split #################################################
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,  # Input data
                                                  y,  # output data
                                                  random_state=1234, # it select random samples
                                                  test_size=0.30)

#########################Model predictions happens X_test############################################
y_predictions=LR.predict(X_test.array.reshape(-1, 1))


######################### Metrics######################################################################

from sklearn.metrics import r2_score,mean_squared_error
R2=r2_score(y_test,y_predictions)
MSE=mean_squared_error(y_test,y_predictions)
RMSE=np.sqrt(MSE)
#accuracy_score(y_test,y_predictions) # it is a regression tech
print("R-sqaure:",R2)
print("MSE:",MSE)
print("RMSE:",RMSE)

$Step-11$:
    
**Save the model**

In [29]:
import pickle
pickle.dump(LR,
            open('linear_wine_model.pkl','wb'))

#Model name=LR
#In which name the model is saving: linear_slaary_model
# extenstion: Pickle
# wb: write in bytes

$Step-12$:

**Load the model**

In [30]:
# Loading model to compare the results
model = pickle.load(open('linear_wine_model.pkl','rb'))
model

LinearRegression()

$Step-13$:
    
**Predictions**

In [31]:
X_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
688,7.7,0.660,0.04,1.6,0.039,4.0,9.0,0.99620,3.40,0.47,9.4
961,7.1,0.560,0.14,1.6,0.078,7.0,18.0,0.99592,3.27,0.62,9.3
726,8.1,0.720,0.09,2.8,0.084,18.0,49.0,0.99940,3.43,0.72,11.1
537,8.1,0.825,0.24,2.1,0.084,5.0,13.0,0.99720,3.37,0.77,10.7
1544,8.4,0.370,0.43,2.3,0.063,12.0,19.0,0.99550,3.17,0.81,11.2
...,...,...,...,...,...,...,...,...,...,...,...
1461,6.2,0.785,0.00,2.1,0.060,6.0,13.0,0.99664,3.59,0.61,10.0
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6
1045,6.9,0.440,0.00,1.4,0.070,32.0,38.0,0.99438,3.32,0.58,11.4
1498,6.6,0.895,0.04,2.3,0.068,7.0,13.0,0.99582,3.53,0.58,10.8
42,7.5,0.490,0.20,2.6,0.332,8.0,14.0,0.99680,3.21,0.90,10.5

In [36]:
X_test.values

array([[ 7.7  ,  0.66 ,  0.04 , ...,  3.4  ,  0.47 ,  9.4  ],
       [ 7.1  ,  0.56 ,  0.14 , ...,  3.27 ,  0.62 ,  9.3  ],
       [ 8.1  ,  0.72 ,  0.09 , ...,  3.43 ,  0.72 , 11.1  ],
       ...,
       [ 6.9  ,  0.44 ,  0.   , ...,  3.32 ,  0.58 , 11.4  ],
       [ 6.6  ,  0.895,  0.04 , ...,  3.53 ,  0.58 , 10.8  ],
       [ 7.5  ,  0.49 ,  0.2  , ...,  3.21 ,  0.9  , 10.5  ]])

In [38]:
len(X_test.columns)

11

In [40]:
model.predict([[1,2,3,4,5,6,7,8,9,10,11]])
# the input columns are 11
# so we need pass 11 values as list

array([-82.48338949])

In [32]:
model.predict(X_test)

array([5.15272674, 5.32546327, 5.63662519, 5.51245819, 6.35588496,
       5.39028618, 5.37580837, 5.94379165, 5.49446987, 6.98211458,
       4.92847919, 5.18177228, 5.73271386, 5.56085417, 5.53985028,
       5.25272042, 4.93424659, 5.12423646, 6.27626835, 5.12589226,
       5.06691612, 5.91039778, 5.1797551 , 5.45854364, 5.72531378,
       6.31002431, 5.30913419, 5.50678991, 6.04808131, 5.47609822,
       4.72291628, 6.20818055, 5.21920961, 5.62421184, 5.55062526,
       5.52259916, 6.36735043, 5.23288886, 5.49938736, 5.80792898,
       5.16587916, 6.13318292, 5.72636822, 5.33537114, 5.63701918,
       4.96463531, 4.88029661, 5.78938553, 6.36333952, 5.56149953,
       4.95005899, 5.75085354, 6.67236186, 6.16951277, 5.34056761,
       5.12096361, 6.19641543, 5.21584694, 6.46449078, 5.25590493,
       5.27667097, 5.17871421, 5.09122333, 5.63083824, 5.01946398,
       6.16336001, 5.7427919 , 6.337122  , 5.28732968, 6.05063646,
       5.7342916 , 5.57340483, 5.21043842, 6.18633591, 5.50678991,
       5.3453067 , 5.99997768, 6.51564794, 4.85375662, 5.04018732,
       5.72499592, 5.59626211, 5.73949584, 5.95489086, 5.34697269,
       4.99839179, 6.13681154, 5.32302661, 6.01068016, 6.12678637,
       6.52768314, 5.39538409, 5.9974906 , 4.99004327, 5.44790697,
       5.86843828, 5.26806983, 6.65075932, 6.61072464, 5.99997768,
       5.37579844, 5.48785095, 4.94241599, 5.53013394, 5.51054593,
       5.25914217, 5.89858025, 5.16978949, 5.40527552, 5.44913755,
       6.38388834, 5.54138872, 6.22755065, 5.35050741, 5.55565805,
       5.69996464, 5.35611312, 5.91795566, 6.84295266, 5.21736143,
       5.93685756, 6.02728227, 5.65516136, 6.33585096, 6.11727608,
       5.10631555, 5.21930664, 6.51527783, 6.29685541, 6.23764222,
       5.2792288 , 5.03871695, 5.88172061, 5.0851889 , 5.27738598,
       6.35828943, 5.89939941, 5.45905811, 5.41928796, 5.57217489,
       5.93356169, 4.83777751, 5.43045252, 5.14580263, 5.75145727,
       5.77227893, 5.20511824, 6.22744476, 6.15111159, 5.37199058,
       5.43837324, 5.77768114, 6.61866538, 6.74493635, 5.99429439,
       5.77421449, 5.71445701, 5.63158268, 6.53617359, 5.61226567,
       6.41524291, 5.85713158, 6.03657959, 5.36589905, 5.79504901,
       6.15045308, 5.34746564, 4.18492552, 5.78179004, 5.9409628 ,
       4.87152252, 5.75689927, 4.97026015, 5.74576868, 6.55745611,
       6.04292031, 5.32973134, 5.52682185, 5.71987688, 4.93131525,
       6.04719996, 5.20606774, 5.85001588, 6.56279324, 5.22784496,
       5.13583528, 6.49406669, 6.67080913, 5.86790849, 6.22543582,
       5.99898464, 5.48676406, 4.68758173, 6.42891816, 5.3780084 ,
       4.72596428, 5.35624776, 6.98166918, 5.30720706, 5.01009976,
       5.9095069 , 5.89788367, 5.74541352, 4.97661924, 6.64061995,
       5.56824532, 5.88970167, 5.10254921, 5.03266072, 4.78859962,
       5.66137988, 5.01756041, 5.70331509, 5.08378929, 5.91679978,
       6.69986908, 5.31928286, 5.34669749, 5.31734828, 5.6188404 ,
       5.6103356 , 5.88657821, 4.82255134, 5.47617034, 5.82141836,
       4.96924459, 5.45555462, 6.15466593, 5.60961275, 5.97937907,
       6.29141847, 5.49532602, 5.7427919 , 5.02129556, 5.42567123,
       5.30376592, 6.44506134, 5.79457654, 5.85840874, 6.40681931,
       5.23356207, 5.09446531, 6.29040996, 5.23133575, 5.20440993,
       4.91613205, 4.85264526, 5.77402591, 6.44998907, 6.27228383,
       5.66752455, 5.77214065, 6.2457379 , 5.01756041, 5.88530413,
       5.46922842, 5.31254547, 5.16197206, 5.84930403, 5.45790288,
       5.45284814, 5.0309555 , 6.11126538, 6.39353084, 5.95035988,
       6.16294412, 6.11799254, 5.859645  , 5.32664826, 5.34056761,
       5.06423962, 5.32051406, 5.43624309, 5.33971951, 5.58178758,
       5.75588456, 6.04024883, 4.91167335, 5.60170434, 5.32877713,
       6.22983414, 5.89614721, 5.93360527, 5.39888101, 5.2739361 ,
       5.73794177, 5.86555862, 5.03944697, 5.32346217, 5.74101128,
       6.40284138, 5.96305686, 4.93108229, 5.90456997, 5.71279268,
       5.61244954, 5.14567686, 5.36421345, 4.96924459, 5.38200614,
       5.93259413, 6.61817345, 5.9401426 , 5.09222651, 6.59461735,
       6.37818219, 5.76677648, 5.00550284, 5.6642651 , 5.09132685,
       5.35617409, 5.0856266 , 5.76205873, 5.58353651, 6.11360811,
       5.26670428, 5.1502229 , 6.35872853, 5.78881572, 5.12077223,
       6.20379015, 5.12846456, 5.245733  , 5.62421184, 5.33216794,
       4.63391647, 6.67080913, 5.30197384, 6.07737771, 5.08945872,
       6.3404451 , 5.00101501, 5.76082175, 4.78681399, 5.43540031,
       5.5933712 , 5.20854044, 5.53965055, 5.51286652, 6.09119691,
       6.89645836, 6.5818963 , 6.51616813, 6.7389971 , 5.13583528,
       5.04542379, 5.55565805, 5.81421595, 5.8596704 , 5.5371316 ,
       5.52159867, 6.08766214, 5.33673345, 5.21641764, 5.5881843 ,
       4.83649958, 6.54755782, 6.15975664, 5.18758997, 5.543044  ,
       6.37948308, 5.27430664, 5.41978692, 5.95011166, 6.15443962,
       5.43156985, 5.17851884, 5.71776488, 5.31049826, 6.29287608,
       5.16405155, 5.51987093, 5.94985843, 5.45261618, 6.1957446 ,
       6.22450256, 6.34398536, 5.02138294, 5.08230935, 5.63470779,
       5.75689927, 5.56268525, 4.61066841, 5.6356401 , 5.91613694,
       4.96621268, 5.10918278, 5.66306872, 4.79517341, 5.79608951,
       6.11360811, 6.23317938, 5.15817553, 5.66531897, 5.37580837,
       5.25189877, 6.5720807 , 5.24409385, 5.55140543, 6.45336013,
       6.40942246, 4.83234267, 5.30326782, 4.96473992, 7.52775146,
       5.42951778, 6.38524949, 6.37419061, 6.63801798, 6.05922706,
       5.73767049, 6.03642831, 4.83223993, 6.24020332, 5.72479784,
       5.18607442, 5.05450429, 5.11697949, 5.13412713, 5.52440323,
       5.64867525, 4.98224538, 6.09363224, 5.44051117, 5.81230694,
       5.46789186, 4.55788622, 6.4346495 , 6.83493526, 5.55577486,
       5.78380845, 6.26550268, 5.16451239, 5.64312174, 5.19935697,
       6.36699511, 4.96641745, 5.86934155, 5.76462945, 6.36547688,
       5.57273104, 5.67822167, 5.3098559 , 5.32346217, 5.80379403,
       5.05273644, 4.89716249, 4.94106077, 4.39448333, 5.35399193,
       5.95011166, 5.47056853, 5.09916641, 6.15419278, 5.32886401,
       5.55946617, 6.39503255, 5.51496826, 5.09226489, 5.98738087,
       6.16951277, 5.66535961, 4.85264526, 5.32570564, 6.08694216,
       5.71886682, 6.18670867, 5.16933689, 5.47617034, 5.1985077 ,
       5.37466118, 5.4969461 , 5.11061722, 5.07457111, 6.43458746,
       5.16307079, 5.55639097, 6.16741756, 5.27142375, 5.67409146])

In [37]:
import os
os.getcwd()

'C:\\Users\\omkar\\OneDrive\\Documents\\Data science\\Naresh IT\\Data science\\Batch-2_July3\\ML python\\Linear_regression'

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [41]:
X.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [42]:
input_cols=['fixed acidity', 'volatile acidity', 'citric acid', 
                'residual sugar','chlorides', 'free sulfur dioxide', 
                'total sulfur dioxide', 'density',
                'pH', 'sulphates', 'alcohol']

#val1=input()
#val2=input()
#val11=input()
#list1=[v1,v2]

list1=[]
for i in input_cols:
    val=input()
    list1.append(eval(val))

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.
1
2
3
4
5
6
7
8
9
10
11

In [43]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [45]:
model.predict([list1])

array([-82.48338949])